### ISSUE TITLE
vue-ui-wheel  animation:false

### ISSUE THREAD

**Issue by ae86yyk** [graphieros/vue-data-ui#100]
When set animation false in vue-ui-wheel, set percentage value again, show incorrect.
![image](https://github.com/user-attachments/assets/d22efb49-ff51-4d21-b1de-870f0a722069)

When set animation true, animation can start from the last value instead of 0?

**Comment by graphieros** [comment]
@ae86yyk 

Thank you for pointing out this issue.
You can upgrade to [v2.3.70](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.70) which fixes the display bug, and also animates from the previous value.
