### ISSUE TITLE
backgroundColor RGBA support

### ISSUE THREAD

**Issue by colaiven** [graphieros/vue-data-ui#109]
many charts have their background colors set, but i cant set transparency, chart look awkward against a gradient image background, 

hope to support RGBA backgroundColor

Thanks!

![image](https://github.com/user-attachments/assets/8f32de33-84e3-4d5c-b1ef-cd29db4c3536)

**Comment by graphieros** [comment]
Hi @colaiven 

Thanks for this issue. It was on my mind for a while, you give me the opportunity to tackle it.

I'll keep you posted when it's done.

**Comment by graphieros** [comment]
@colaiven 

You can upgrade to [v.2.3.77](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.77) which adds support for transparent colors.

**Comment by colaiven** [comment]
> @colaiven 
> 
> 
> 
> You can upgrade to [v.2.3.77](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.77) which adds support for transparent colors.
> 
> 
> 
> You can pass RGBA, HSLA, or HEX colors with alpha channel in dataset and config props.
> 
> 
> 
> The chart builder on the documentation website was updated too. See #111 

Great, thank you for making such a great product！
