### ISSUE TITLE
It's a little weird in curve mode, it's supposed to be smooth instead of down

### ISSUE THREAD

**Issue by Sharang-heng** [graphieros/vue-data-ui#114]
I want 
![img_v3_02gk_013c3015-0ba4-47e8-96d8-7b2e9de9ac2g](https://github.com/user-attachments/assets/d4bf0962-44b2-427f-be7b-08c2cc38809e)
in effect
![img_v3_02gk_82fd38f1-cb97-4766-b135-ff510683618g](https://github.com/user-attachments/assets/8819df02-166a-48fa-ae49-c25261f4d2ca)
![img_v3_02gk_9c15f0b1-bde9-40ff-84ae-4d45bff9530g](https://github.com/user-attachments/assets/8072a89e-aebc-4de4-9752-bbcb517f4a27)

**Comment by graphieros** [comment]
Hi @Sharang-heng 

Thank you for this issue, it was indeed very critical.

You can upgrade to [v2.3.88](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.88) which fixes the smooth line algorithm to avoid dips.
