### ISSUE TITLE
If I don't use pdf and screenshots, can you not package jsPDF and html2canvas?

### ISSUE THREAD

**Issue by ae86yyk** [graphieros/vue-data-ui#116]
If I don't use pdf and screenshots, can you not package jsPDF and html2canvas? Reduced packing volume.

**Comment by graphieros** [comment]
Not really.
What I can do is make sure html2canvas and JsPdf are not downloaded by the end user if printing is not used.

**Comment by graphieros** [comment]
[v2.3.90 ](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.90) is a partial answer to your issue.
html2canvas and JsPdf will be downloaded by the client only if the print functionalities are used. Therefore, setting `config.userOptions.buttons.pdf` and `config.userOptions.buttons.img` to false will hide PDF and IMG buttons in the menu.

I understand it is not exactly what you expected with your issue, but the js chunks shipped to the end user will be smaller, which is more important than the package size.
