### ISSUE TITLE
"X axis labels" is not controlled by "Show labels"

### ISSUE THREAD

**Issue by jimnxj** [graphieros/vue-data-ui#119]
I'm researching the VueUiXy component, found that "X axis labels" is not controlled by "Show labels",  The labels on the x-axis cannot be displayed perfectly.

![image](https://github.com/user-attachments/assets/03f7497a-6549-4b95-ad03-1f3896b56fae)

![image](https://github.com/user-attachments/assets/ec573d01-e645-4a50-b02d-f9c47902d76d)

**Comment by jimnxj** [comment]
Refer to the second screenshot, the right frame line is not displayed correctly.

**Comment by graphieros** [comment]
Hi @jimnxj 

No issue here.

Show labels controls data labels, not axis labels.
Axis labels are not shown in they remain empty.

As for the crop effect, just add some padding bottom in the padding section.

**Comment by jimnxj** [comment]
Hi @graphieros 
Thanks! but how about the 2nd question?
The border lines should not run through the data graph on the x-axis.

**Comment by graphieros** [comment]
That's because it should be set on 'middle' if you use bars.
