### ISSUE TITLE
Hello, I want to change the position of the chart legend, e.g. to put it on the left, on top, etc

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#124]
For example, the picture looks like this
![微信图片_20241203132228](https://github.com/user-attachments/assets/ac23fba0-6943-47be-9cbd-2e72fd0fddb9)
![微信图片_20241203132228](https://github.com/user-attachments/assets/7b6910f8-724f-4fbd-a099-daa7ff0bfbf3)

**Comment by graphieros** [comment]
Hi @khcshell 

You can use the #legend slot, and apply css on your own legend:

1. set legend.show: false
2. use the legend slot (here is an example with the VueUiXy component):

```html
<div style="position: relative">
  <VueUiXy :dataset="dataset" :config="config">
    <template #legend="{ legend }">
      <div :style="{ /* Apply your style here, position absolute to place it where you want */}">
        <div v-for="datapoint in legend" :style="{ display: 'flex', flexDirection: 'row', gap: '1rem'}">
          <div :style="{ backgroundColor: datapoint.color, height: '24px', width: '64px' }" @click="datapoint.segregate()"/>
          <div>{{ datapoint.name }}</div>
        </div>
      </div>
    </template>
  </VueUiXy>
</div>
```

**Comment by graphieros** [comment]
@khcshell 

I just added an [implementation example](https://vue-data-ui.graphieros.com/customization#legend-slot) on the documentation website.

**Comment by khcshell** [comment]
@graphieros thanks
