### ISSUE TITLE
[VueUiTreemap] Fontsize too big when  use scaleDraw-animation on parent div and enable responsive

### ISSUE THREAD

**Issue by colaiven** [graphieros/vue-data-ui#126]
bug source:
```
<div style="width: 500px;height: 400px;animation: scaleDraw 1.2s ease-in-out;" >
      <VueDataUi :component="'VueUiTreemap'" :dataset='[{
        name: "Parent1",
        value: 100,
        children: [
            {name: "P1 C1", value: 30},
            {name: "P1 C2", value: 20},
            {name: "P1 C3", value: 10}
        ]
      }]' :config="{responsive: true,userOptions:{show: false}}"/>
    </div>
```

look
![image](https://github.com/user-attachments/assets/f16f8aec-2c65-4743-9766-230555e0c1d3)

**Comment by colaiven** [comment]
i konw that
but its not a use problem

**Comment by graphieros** [comment]
It's not a bug either :)

**Comment by colaiven** [comment]
> Hi @colaiven 
> 
> 
> 
> You can manage fontSize in the config:
> 
> 
> 
> ```
> 
> const config = ref({
> 
>     responsive: true,
> 
>     userOptions:{show: false},
> 
>     style: {
> 
>         chart: {
> 
>             layout: {
> 
>                 labels: {
> 
>                     fontSize: 12
> 
>                 }
> 
>             }
> 
>         }
> 
>     }
> 
> })
> 
> ```
> 
> 
> 
> You can also manage your own content through the #rect slot ([see documentation page](https://vue-data-ui.graphieros.com/docs#vue-ui-treemap) in the slots tab), if this is not enough.

i konw that
but its not a usage question
the question is when i use css animation, you can run my code

**Comment by graphieros** [comment]
There is no css referring to your inline styles in your code.

**Comment by colaiven** [comment]
> There is no css referring to your inline styles in your code.

<div style="width: 500px;height: 400px;animation: scaleDraw 1.2s ease-in-out;" >

**Comment by colaiven** [comment]
> There is no css referring to your inline styles in your code.

```
first line

<div style="width: 500px;height: 400px;animation: scaleDraw 1.2s ease-in-out;" >
...

```

**Comment by graphieros** [comment]
Yes, but your `animation: scaleDraw 1.2s ease-in-out;` is not referring to any keyframe animation, you did not provide the keyframes, no nothing to replicate on my side.

**Comment by colaiven** [comment]
> Yes, but your `animation: scaleDraw 1.2s ease-in-out;` is not referring to any keyframes animation, you did not provide the keyframes, no nothing to replicate on my side.
> 
> 

The bug appears in this line
wait me creat a online link for you

**Comment by colaiven** [comment]
> Yes, but your `animation: scaleDraw 1.2s ease-in-out;` is not referring to any keyframes animation, you did not provide the keyframes, no nothing to replicate on my side.
> 
> 

I'm so sorry, I made a mistake, scaleDraw  is my own definition，It's a scale transform.
```
@keyframes scaleDraw {
  from{transform: scale(0.2)}
  to{transform: scale(1)}
}
```

online source:
https://stackblitz.com/edit/vitejs-vite-jufprh?file=src%2FApp.vue

**Comment by graphieros** [comment]
You can solve this using the slots:
```

<script setup>
import { VueDataUi } from 'vue-data-ui';
import 'vue-data-ui/style.css';
</script>

<template>
  <div
    style="
      width: 500px;
      height: 400px;
      animation: scaleDraw 1.2s ease-in-out;
      border: 2px solid red;
    "
  >
    <VueDataUi
      :component="'VueUiTreemap'"
      :dataset="[
        {
          name: 'Parent1',
          value: 100,
          children: [
            { name: 'P1 C1', value: 30 },
            { name: 'P1 C2', value: 20 },
            { name: 'P1 C3', value: 10 },
          ],
        },
      ]"
      :config="{
        responsive: true,
        userOptions: { show: false },
        style: {
          chart: { layout: { labels: { showDefaultLabels: false } } },
        },
      }"
    >
      <template #rect="{ rect, shouldShow, fontSize, isZoom, textColor }">
        <div style="height: 100%; width: 100%; font-size: 4px">
          {{ rect.name }}: {{ rect.value }}
        </div>
      </template>
    </VueDataUi>
  </div>
</template>

<style>
@keyframes scaleDraw {
  from {
    transform: scale(0.2);
  }
  to {
    transform: scale(1);
  }
}
</style>

```

**Comment by colaiven** [comment]
Is this a problem？
@graphieros 🫡

**Comment by graphieros** [comment]
Not really.
I intentionally override outside transitions on the components, to avoid interferences with libraries.
This use case is very specific, you rarely put this kind of animation on a chart, but the #rect slot does provide a solution.

**Comment by colaiven** [comment]
> Not really.
> 
> I intentionally override outside transitions on the components, to avoid interferences with libraries.
> 
> This use case is very specific, you rarely put this kind of animation on a chart, but the #rect slot does provide a solution.

okok thanks verymuch😁
