### ISSUE TITLE
Two questions about VueUiCarouselTable

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#129]
Hello, I have two questions for my advice
1. In VueUiCarouselTable, can the slider on the right provide an option not to hide, but to display all the time, so that the slider will not cause the phenomenon of squeezing the table.
2. Unless the function is called, e.g. pauseAnimation, can you give an example, thank you very much
![11111111](https://github.com/user-attachments/assets/962edc46-6e65-4527-ad5f-851724b1638f)

**Comment by khcshell** [comment]
![Uploading 222222222222222.png…]()

**Comment by khcshell** [comment]
![222222222222222](https://github.com/user-attachments/assets/66e5824e-4772-40da-b4f6-b56ebab041c8)

**Comment by khcshell** [comment]
The red box, can I hide it when I don't need it, so it's more beautiful
![333333333333333](https://github.com/user-attachments/assets/c94a7f1f-d644-4c73-8ea2-61a7a6869a94)

**Comment by graphieros** [comment]
Hi @khcshell 

1. I can add an option to always show the scrollbar
**2. I don't understand your second point**
**3. I don't understand why you post the screenshot of the documentation**
4. I can add an option to hide the caption when it is not used

**Comment by khcshell** [comment]
@graphieros Yes, I don't call the exposure method pauseAnimation alone, like how to write js to make the chart pause

**Comment by khcshell** [comment]
@graphieros I'd like to have an example to use the exposed method

**Comment by khcshell** [comment]
@graphieros Thanks a lot, plus I also need the config option to always not show the scrollbar, I can scroll with the mouse and auto-scroll

**Comment by graphieros** [comment]
@khcshell noted!

**Comment by graphieros** [comment]
@khcshell you can upgrade to [v2.4.27](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.27) which adds config options to control scrollbar.

For your use case, set `config.scrollbar.hide: true`

Also, to hide the caption area:
- set `config.caption.text: ""`
- set `config.userOptions.show: false`
