### ISSUE TITLE
VueUiTableSparkline,Background color issues

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#133]
![image](https://github.com/user-attachments/assets/28cfd2fa-8d42-4ce2-9142-068cb2de9f6c)
![image](https://github.com/user-attachments/assets/56749de9-05bf-4fe2-8edb-8b4e2acb5c35)
As you can see, the background color has only changed by half, and how the other half has changed

**Comment by graphieros** [comment]
@khcshell 

This problem was caused by the documentation website which had some css overriding styles, it was not an issue with the component.

The documentation website is updated.

**Comment by khcshell** [comment]
@graphieros 
![image](https://github.com/user-attachments/assets/3ff0d971-ce49-4ac0-9e95-82f1493bd65e)

1. Is it possible to choose not to display the dots in front?
2. The outline here is unevenly thick
3. The sparkline behind the mouse can be moved up to see whether the Tooltip can be displayed

**Comment by graphieros** [comment]
Can you explain .3 ? I don't understand.

**Comment by khcshell** [comment]
Hover over the chart to display a Tooltip，like this
![image](https://github.com/user-attachments/assets/32a224ad-1fd1-45ac-b12e-24619666e7b5)

**Comment by khcshell** [comment]
I can choose to show or not to display it as a vertical comparison

**Comment by graphieros** [comment]
1. I will add a config option to show or hide
2. Will fix
3. Not sure yet, need to think about it.

**Comment by khcshell** [comment]
explain 3 Just an idea, not very important

**Comment by graphieros** [comment]
It's a good idea, that's why I will think about it ^^

**Comment by graphieros** [comment]
@khcshell 

You can upgrade to v2.4.31 with the following improvements for VueUiTableSparkline:

- new config attribute to hide color marker in first TD:

```ts
config.tbody.showColorMarker: boolean; // default: true
```

- fix outline issue
- improve selection behaviour (maybe it can be improved, this will do for now)

**Comment by graphieros** [comment]
@khcshell can you elaborate on the expected behaviour when it is turned off ?

**Comment by khcshell** [comment]
when it is turned off ，Just revert to the previous style,Because, with a background color, it would be weird to add a color, and I can turn on this feature when the background is white

**Comment by khcshell** [comment]
@graphieros when it is turned off ，Just revert to the previous style,Because, with a background color, it would be weird to add a color, and I can turn on this feature when the background is white

**Comment by graphieros** [comment]
I will add options to control the color when the cell is selected (choice to use series colors or a custom color, with a custom opacity). It is important to keep highlight on the cells when  hovering the table or the sparkline charts

**Comment by graphieros** [comment]
@khcshell 
You can upgrade to v2.4.32, which adds the following config attributes to VueUiTableSparkline:

```ts
config.tbody.selectedColor.useSerieColor: boolean; // default: true
config.tbody.selectedColor.fallback: string; // default: #E1E5E8, applied when useSerieColor is set to false. A color with transparency can be passed, for example: #FFFFFF10 
```

**Comment by khcshell** [comment]
@graphieros hi,As you can see, after both tbody and thead are set to outline, there will be a problem of misalignment of weight, in addition. sparkline
Whether the content text can be set to the size of the margin (from the border position), so that it can be adjusted to make it look more beautiful
![image](https://github.com/user-attachments/assets/d45e3b18-870c-4330-a1bd-92b951696229)

**Comment by khcshell** [comment]
![1733963255622](https://github.com/user-attachments/assets/9772fae0-1950-4eee-8e31-5a47784171d4)

**Comment by khcshell** [comment]
@graphieros 
![image](https://github.com/user-attachments/assets/bdd8bc13-fc4d-43ec-9692-cebf7ee6bea9)
![image](https://github.com/user-attachments/assets/8b00385c-98d7-432e-8083-4d10f916b6e3)
are set to right, but it doesn't work here and the same goes for centering

**Comment by graphieros** [comment]
@khcshell 
You can upgrade to v2.4.35:
- bigger chart size
- fix textAlign issues
- fix THEAD outline issue

**Comment by khcshell** [comment]
> * bigger chart size
@graphieros 
What I think is that the chart size can be resized like the font. By default, it will always look imperfect. For example, now I want the width to be larger while keeping the height unchanged. Can we add an option to adjust the distance up, down, left, right

**Comment by graphieros** [comment]
@khcshell 
You can upgrade to v2.4.37 which adds config attributes to control chart dimensions:

```ts
config.sparkline.dimensions.width: number; // default: 150
config.sparkline.dimensions.heightRatio: number; // default: 1
```
You can adjust both these attributes to get the result you need.
