### ISSUE TITLE
VueUiCarouselTable

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#134]
![image](https://github.com/user-attachments/assets/4c193ebf-aef3-4347-aad6-225e096028b9)

1.When the animation is paused, there will be a blank space, which is very aesthetic, can it be improved to display normal data, at least the background color。
2、Expose the call method of the function,I want him to pause directly after the rendering is completed.,But it doesn't seem to work.,The output is undefined.,It's okay to delay 1 second execution.,Please tell me how to write.
![image](https://github.com/user-attachments/assets/e3abc495-7c7f-4ce2-9599-439514fec3da)

**Comment by graphieros** [comment]
@khcshell 

Try adding a small timeout:

```
onMounted(() => {
    setTimeout(() => {
        toggleAnimation()
    }, 100)
})
```

The blank space is due to the fact that the TR is not visible when it is overflowing the THEAD. It is necessary for the use cases where the THEAD has a transparent background, to avoid the overflow. The only solution I can suggest is for you to harmonize background colors.

**Comment by khcshell** [comment]
onMounted(() => {
    setTimeout(toggleAnimation, 100)
})
This method can solve the problem temporarily, but it is not perfect, because the PC performance is different, the rendering time is different, and the latency time is not uniform

**Comment by khcshell** [comment]
@khcshell onMounted(() => {
setTimeout(toggleAnimation, 100)
})
This method can solve the problem temporarily, but it is not perfect, because the PC performance is different, the rendering time is different, and the latency time is not uniform

**Comment by graphieros** [comment]
Ok so instead you can setup a watch on the ref, to trigger the toggleAnimation when it is true.

**Comment by khcshell** [comment]
> 空白处是由于 TR 在溢出 THEAD 时不可见。对于 THEAD 具有透明背景的用例，有必要避免溢出。我能建议的唯一解决方案是让你协调背景颜色。
@graphieros Do you mean to set the background of TD to be fully transparent? I tried it and it didn't work

**Comment by khcshell** [comment]
![image](https://github.com/user-attachments/assets/dfac23b0-9e4a-4128-9fe1-8f980b47ac19)
![image](https://github.com/user-attachments/assets/bbc50dae-01a9-4769-a727-ef5b45e17a68)

like this，You can show half of it, but don't show it blank, even if it's just the background color

**Comment by graphieros** [comment]
Is it possible for you to show a video ?
I still don't understand how you get this spacing.
When I pause onMounted, I don't get the spacing

**Comment by khcshell** [comment]
https://github.com/user-attachments/assets/5bd90781-c0c0-4cfc-b865-ca9924ea2168

You see, I've set the background color, and the white color that appears can be seen by slowly moving after pausing until it's completely displayed

**Comment by graphieros** [comment]
For the sake of testing, can you try adding the following css in a style tag:

table.vue-data-ui-carousel-table {
    background: blue !important;
}

If this does set the table bg color then I must add an additional config attribute for that.

**Comment by khcshell** [comment]
@graphieros Do you understand the question I'm talking about

**Comment by khcshell** [comment]
![image](https://github.com/user-attachments/assets/63f62ac0-005c-4add-98d0-a466a2f3afee)
![image](https://github.com/user-attachments/assets/fa209832-b425-4746-8bcd-0cb6e5b65295)
OK。It works, I can set this to the background color to transition, you can add this to the settings

**Comment by graphieros** [comment]
@khcshell 
You can upgrade to v2.4.36, which adds the following config attribute to VueUiCarouselTable:

```ts
config.tbody.backgroundColor: string; // default: "#FFFFFF"
```
