### ISSUE TITLE
Question: Zoom Slider default number

### ISSUE THREAD

**Issue by GohChunFeng** [graphieros/vue-data-ui#137]
Hi, recently just found out this interesting library to render charts and the documentation are very well written.
Currently I playing around with the vue-ui-stackbar and faced some issue and wondering how am i able to solve it.
![image](https://github.com/user-attachments/assets/7bc979a4-de0f-4025-930d-b4c7a616f56e)
I took this image from the documentation and I would like to ask is it possible to control the initial value for the zoom slider? For example can it be set to show only 3 out of 6 bars? like this on the initial load: 
![image](https://github.com/user-attachments/assets/9ea8fd9d-7c55-4cc0-83f4-86f11a887aa6)
Thanks!

**Comment by graphieros** [comment]
Hi @GohChunFeng 

Do you mean a missing feature would be a configuration to set the initial zoom state ?

Thank you for your encouraging comments:)

**Comment by GohChunFeng** [comment]
> Hi @GohChunFeng
> 
> Do you mean a missing feature would be a configuration to set the initial zoom state ? (start index and end index)
> 
> Thank you for your encouraging comments:)

Thanks for the quick reply! Yes, can we have the configuration to set the start and end index?

**Comment by graphieros** [comment]
@GohChunFeng 

Ok, this is indeed a feature I was thinking of adding, so your request comes at the right time.
I will work on this for the next release. It will be applied on all charts which bear this zoom functionality.

I'll keep you posted when it is done.

**Comment by graphieros** [comment]
@GohChunFeng 

You can upgrade to [v2.4.42](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.42), which adds config attributes to setup startIndex and endIndex on the zoom:

```ts
zoom.startIndex: number | null; // default: null
zoom.endIndex: number | null: // default: null
```
