### ISSUE TITLE
Questions: Customization of x-axis label

### ISSUE THREAD

**Issue by GohChunFeng** [graphieros/vue-data-ui#139]
Hi, thanks for the previous quick update on the start and end index for zoom slider. It working now and fit my usecase.
I would like to ask is it possible for the chart to have customization on the label name area?
![image](https://github.com/user-attachments/assets/51a4b816-e701-4d0c-99a3-a65dce95ac3e)
For example, can the chart have click event on the label name and probably can apply a customFormat(like currently used in the tooltip?
Thanks!

**Comment by graphieros** [comment]
@GohChunFeng 

What would be the use case for a customFormat ? You can already format your labels inside grid.x.timeLabels.values.

I can add click events on timeLabels. Can I ask if you can elaborate on the use case for such a click event on time labels ?

**Comment by GohChunFeng** [comment]
@graphieros For example, I am thinking of passing array object into the grid.x.timeLabels.values = [{...}, {...}, {...}], so each object has id, name and subname, for display maybe the name on the first line of the label and subname on the second line of the label with different font size etc, and when click happend it will just pass the whole object (in this case is the id, name and subname) so i can use the object details like the id to pass into an api or some action. Thanks!

**Comment by graphieros** [comment]
@GohChunFeng 

What I can do is a click event that exposed the formatted dataset at a given index  which you  could then use to make API calls from a find in your local data. It is more flexible than imposing a format from outside the library.

For example:

```js
const localDataForAPI = computed(() => {
    return [
        { name: 'JAN', id: 'A', additionalInfo: 'ABC'},
        { name: 'FEB', id: 'B', additionalInfo: 'BCD'},
        { name: 'MAR', id: 'C', additionalInfo: 'CDE'}
    ].map((d, i) => {
        return {
            ...d,
            absoluteIndex: i
        }
    })
})

// absoluteIndex as an example of possible exposed data, but more info can also be exposed, as the series and values at selected index
function onLabelClick({ absoluteIndex }) {
    const target = localDataForAPI.value.find(t => t.absoluteIndex === absoluteIndex);
    // Do something with the target
}
```

```html
<VueUiStackbar
  :dataset="dataset"
  :config="config"
  @selectTimeLabel="onLabelClick"
/>
```

As for the additional formatting of time labels, this is tricky.
This is SVG, text elements have a different behavior as divs.
A solution would be to use scoped slots, exposing the label data (x and y position, absolute index), but you would have to manage your own SVG text elements or TSpan elements.
 For example:

```html
<VueUiStackbar
  :dataset="dataset"
  :config="config"
  @selectTimeLabel="onLabelClick"
>
  <template #timeLabel="{ x, y, absoluteIndex, textAnchor, fontSize }">
     <text :x="x" :y="y" fill="black" :text-anchor="textAnchor" font-size="fontSize">{{ localDataForApi.find(d => d.absoluteIndex === absoluteIndex).text }}</text>
    <text x:="x" :y="y + fontSize" fill="grey" :text-anchor="textAnchor" font-size="fontSize * 0.8">{{ localDataForApi.find(d => d.absoluteIndex === absoluteIndex).additionalInfo }}</text>
  </template>
</VueUiStackbar>
```

Using scoped slots would make it more flexible for all users.

**Comment by GohChunFeng** [comment]
@graphieros thank you for your explaination, the scoped slots looks good, is the same with the legend slot and instead of normal div it just requires the svg elements correct(shouldn't be a problem i think)? and i saw the scoped slots can also bind the click event which fit my usecase also, these solution looks good to me. Thanks!

**Comment by graphieros** [comment]
@GohChunFeng yes, scoped slot as I indicated as an example works as expected. You can set your own click events where you need (in the example, it is set on the g element).
I will work on that feature, which needs to be applied on other types of charts where time labels are used.

I will keep you posted when it is ready.

**Comment by graphieros** [comment]
@GohChunFeng 
You can upgrade to v2.4.43

I have not yet updated the documentation website, but it will work as explained previously
