### ISSUE TITLE
How can I display the comment labels from examples?

### ISSUE THREAD

**Issue by TobiZog** [graphieros/vue-data-ui#140]
I've trying to create a VueUiXy chart with some comments displayed, like on the example on the official documentation website:

![image](https://github.com/user-attachments/assets/b7025f37-8f69-4566-8bac-eee8639c6ee1)

But I the two cards doesn't appear. I've tried exactly the same datasets and configuration from the homepage. This is the result (with mouse hovering):

![image](https://github.com/user-attachments/assets/a24fc5c8-2cd7-4969-9409-23a24b672340)

How can I display the two cards permanently?

Thank you for your work!

**Comment by graphieros** [comment]
Hi @TobiZog :)

You need to use the #plot-comment scoped slot:

```html
<VueDataUi :component="VueUiXy" :dataset="dataset" :config="config">
  <template #plot-comment="{ plot }">
   <!-- Value checks are hardcoded here but could be compared to your max and min values from the dataset passed to the component -->
    <div v-if="plot.value === 140" class="text-black dark:text-[#CCCCCC] w-full flex flex-col place-items-center text-xl bg-[#FFFFFF] dark:bg-[#4A4A4A] py-2 rounded shadow-md border border-app-green">
      <VueUiIcon name="smiley" stroke="#42d392" :size="30"/>
        {{ plot.comment }}
    </div>
    <div v-else-if="example.component === 'VueUiXy' && plot.value === 12" class="text-black dark:text-[#CCCCCC] w-full flex flex-col place-items-center text-xl bg-[#FFFFFF] dark:bg-[#4A4A4A] py-2 rounded shadow-md border border-app-orange">
      <VueUiIcon name="moodFlat" stroke="#FF6600" :size="30"/>
        {{ plot.comment }}
    </div>
  </template>
</VueDataUi>
```

The code should be displayed on the documentation website. I'll add this.

**Comment by graphieros** [comment]
@TobiZog 

Thanks to your question, I improved the examples page to show when a slot is used, as just copying the dataset and config is not enough in this case.

![image](https://github.com/user-attachments/assets/f1ea3f3d-786c-4c50-a0a8-1fcbe5903fae)
