### ISSUE TITLE
VueUiGauge增加配置 - Segment labels

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#142]
![1734759501661](https://github.com/user-attachments/assets/61eff836-a9b5-448c-b080-c1ba15b38a83)
![1734759474809](https://github.com/user-attachments/assets/15610299-1c04-4000-a9c5-c66891d1f840)
One such meter is needed. Is it possible to add configuration options from this VueUiGauge to achieve a similar effect

**Comment by graphieros** [comment]
Hi @khcshell 

This is a good idea.
I will keep you posted when the update is available.

**Comment by graphieros** [comment]
@khcshell 

You can upgrade to [v2.4.45](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.45) which adds support for segment labels.

**Comment by khcshell** [comment]
@graphieros Whether the gap between the two colors can be set, there is a time when the gap is too small

**Comment by khcshell** [comment]
@graphieros If I don't use the serie color, can I customize the segment color?

**Comment by graphieros** [comment]
> @graphieros Whether the gap between the two colors can be set, there is a time when the gap is too small

What do you mean ?


> @graphieros If I don't use the serie color, can I customize the segment color?

Yes, it's the color attribute that takes precedence when `useSerieColor:false `

**Comment by khcshell** [comment]
![image](https://github.com/user-attachments/assets/c24a0d8a-ed18-4469-aa81-56ce9fb0947c)
Like this, I mean is the possibility of choosing a few styles for the middle separation of the two paragraphs, so that it looks a little richer

**Comment by graphieros** [comment]
@khcshell 
I'll see what I can do.
Can't promise this will be done, as I'm satisfied with the current style.

**Comment by graphieros** [comment]
@khcshell 
Ok, I'll do it, looks like a good option to have indeed

**Comment by graphieros** [comment]
@khcshell 

Would this be suitable for your use case ?

![image](https://github.com/user-attachments/assets/f09ec0f2-ef35-440c-924f-4ea153f7badb)

- color, thickness, label placements are all customizable.

**Comment by khcshell** [comment]
OK。verynice

**Comment by graphieros** [comment]
@khcshell 

You can upgrade to [v2.4.47](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.47)

An example was added [here](https://vue-data-ui.graphieros.com/examples/categories#vue-ui-gauge) so you can copy the config.
