### ISSUE TITLE
VueUiTableSparkline   Several problems encountered

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#144]
![image](https://github.com/user-attachments/assets/c079538e-261b-410b-b42d-1b136115ad01)
1.As shown in the figure, when you click on the sort, there will be a chamfered grid around it, which should be the wrong display
2.Click sorting,It will cause the grid to be stretched open because of the appearance of the arrow,Affect the size of the layout,My suggestion is 1,The sorting function is optional,When you turn it off, the arrow will not be displayed,Turn on this function Sorting arrow has always existed,This problem can be avoided
2. Turn off the sorting function for some columns, because some columns don't need to be sorted, and some data columns may need to be sorted

**Comment by graphieros** [comment]
@khcshell 
1. I cannot reproduce
2. ok
3. ok

**Comment by graphieros** [comment]
@khcshell 

You can upgrade to [v2.4.48](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.48).
Explanations in the release.

[Documentation website is up to date](https://vue-data-ui.graphieros.com/docs#vue-ui-table-sparkline)

**Comment by khcshell** [comment]
@graphieros 
1.The icons in forward order and reverse order should be different, for example, in positive order ⬆, in reverse order ⬇, not now, which would ⬆⬇ be confusing.
2. I didn't find a feature that could turn off sorting, because this feature is not used every time
3. I also can't find to turn off the sorting of some columns, for example, I only need the last 2 columns to sort, then the front column has a sorting function is not suitable

**Comment by graphieros** [comment]
@khcshell 
Everything is explained on the release.

```
sortedDataColumnIndices: [], // use indexes of columns to sort
sortedSeriesName: false,
sortedSum: false,
sortedAverage: false,
sortedMedian: false,
resetSortOnClickOutside: false,
```

**Comment by khcshell** [comment]
@graphieros 
I see, This is great
1.The icons in forward order and reverse order should be different, for example, in positive order ⬆, in reverse order ⬇, not now, which would ⬆⬇ be confusing.
Will this be changed?

**Comment by graphieros** [comment]
Yes, I'm working on it

**Comment by khcshell** [comment]
@graphieros 
![image](https://github.com/user-attachments/assets/17358e3b-546b-4168-833c-d134e504e401)
Do you think it would be better to make the forward and reverse order 2 buttons clicked, and the two are mutually exclusive? If they are all canceled, the original order will be maintained

**Comment by graphieros** [comment]
@khcshell 

If I put 2 buttons up and down, what do you think about this behavior:

- click UP once : sort up
- click UP a second time: restore order

And:
- click UP once: sort up
- click DOWN once: sort down

I'm just afraid buttons are very close in your design, misclick could be easy and frustrating.

**Comment by khcshell** [comment]
@graphieros 
click UP once: sort up ，click UP second: Cancel sort up
click DOWN once: sort down，click DOWN second: Cancel  sort down
and UP, DOWN, click on one, and the other will be automatically canceled. Mutually exclusive

In addition, I recommend placing buttons left and right, it is easy to click on the upper and lower stages, and the spacing between the left and right can be adjusted to avoid this problem

**Comment by graphieros** [comment]
@khcshell 

[DOWN] { label } [UP] ?

**Comment by khcshell** [comment]
@graphieros 
![image](https://github.com/user-attachments/assets/5070578b-3cf2-452e-a80d-2de413f3b5d8)
1. Click on A to sort forward, then click on A to cancel the forward sort, and in the same way click on B to reverse the sort, and then click on B to cancel the reverse sort
2. When you click on A, B will automatically uncheck the state, and when you click on B, you will uncheck the state at A to ensure that the forward and reverse directions will not be activated at the same time
3. As shown in the figure, the interval can be adjusted in the middle, so that you will not click on it wrongly

**Comment by khcshell** [comment]
like this 
![image](https://github.com/user-attachments/assets/147ca1c0-1892-4c2c-bce6-eceb99ad7031)

**Comment by graphieros** [comment]
Ok, I'll just expose a css class for these buttons

**Comment by graphieros** [comment]
@khcshell 

You can upgrade to v2.4.52

**Comment by khcshell** [comment]
@graphieros 
expose a css class for these buttons

Can you write me an example? I didn't succeed in this adjustment

**Comment by graphieros** [comment]
@khcshell 

https://stackblitz.com/edit/vitejs-vite-m4jtitod?file=src%2FApp.vue

Just get the classes through inspection, and force styles.
