### ISSUE TITLE
[FEATURE REQUEST] When the mouse passes over the chart, the userOptions operation menu is displayed

### ISSUE THREAD

**Issue by FearlessPeople** [graphieros/vue-data-ui#148]
**Is your feature request related to a problem? Please describe.**
In a dashboard scenario, there are multiple charts, and if each chart defaults to displaying the userOptions operation menu, it is obviously not very aesthetically pleasing.

**Describe the solution you'd like**

When the mouse passes over the chart, the userOptions operation menu is displayed

**Describe alternatives you've considered**
I once considered not displaying userOptions by default and adding the onmouseover event myself, but this only displayed the thumbnail menu of userOptions without expanding the button. I think this effect is not very good

**Additional context**
![image](https://github.com/user-attachments/assets/fd7e2916-3d61-42b5-ae82-292c21a1dcc9)

**Comment by graphieros** [comment]
@FearlessPeople 

2 precisions before I consider working on your good suggestion:

1. When the mouse enters the chart:
  - only the burger menu is displayed. It is still necessary to click on it to open the menu. I don't wish to force its open state when hovering the chart
 
2. When the menu is open, and the mouse leaves the chart:
  - Two behaviors are possible:
    a.  leave the state of the menu unchanged. In this scenario, when the user hovers the chart again, the menu state is the same as when they left it.
    b. force the closing of the menu

I'm considering adding 2 config options for userOptions:
```ts
showOnHover: boolean; // default: false, to keep current behavior and avoid breaking change
closeOnChartMouseOut: boolean; // default: false, to keep current behavior and avoid breaking change
```

Let me know if you have additional ideas before I work on this.

**Comment by FearlessPeople** [comment]
Thank you, I think the two additional configuration items you added should meet my needs

**Comment by graphieros** [comment]
@FearlessPeople 

Ok great.
The basic feature is ready, but today is special (Christmas) so expect the update to be shipped tomorrow.

**Comment by FearlessPeople** [comment]
@graphieros Great, I'm glad to hear that the basic feature is ready. I understand it's Christmas today, so no worries! I'll look forward to the update being shipped tomorrow. Wishing you a Merry Christmas and a joyful holiday season!

**Comment by graphieros** [comment]
Hhi @FearlessPeople 

You can upgrade to v2.4..51 to use the updated configuration.

```ts
userOptions: {
  show: boolean, // Not new. Has to be true for these new options to be applied. Is true by default
  showOnChartHover: boolean; // New option. Default: false. Set to true to only show the burger menu when hovering the component
  keepStateOnChartLeave: boolean; // New option. Default: true. Set to false to always close the menu when hovering out the component
}
```

I'm currently updating the documentation website.
