### ISSUE TITLE
[BUG]'Nan%' was wrongly displayed in Stackbar

### ISSUE THREAD

**Issue by jimnxj** [graphieros/vue-data-ui#150]
1. if the total value of a series is 0, 'Nan%' will be displayed
2. Could there be a setting option to choose whether to display it or not when the item value is 0?

![image](https://github.com/user-attachments/assets/064f15c2-757f-4f61-bc66-7b0278b08d83)
![image](https://github.com/user-attachments/assets/2b803bc0-8dcd-4f6f-9cce-6e8c0eac770d)

**Comment by graphieros** [comment]
@jimnxj 

You can upgrade to [v2.4.57](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.57) which fixes NaN% and adds config options to hide or show empty values or percentages:

```ts
config.style.chart.bars.dataLabels.hideEmptyValues: boolean; // default: false
config.style.chart.bars.dataLabels.hideEmptyPercentages: boolean; // default: false
```
For your use case, you can set` true` for both.

**Comment by jimnxj** [comment]
Seems there is

**Comment by graphieros** [comment]
@jimnxj 
Thanks, I fixed the labels. Hasty copy pasting^^
