### ISSUE TITLE
how to customize chart labels

### ISSUE THREAD

**Issue by sombriks** [graphieros/vue-data-ui#24]
i am making use of prefix and suffix but i still present the percentage.

is there a way to present another value (i have the absolute value, would like to present it instead of the percentage) in lables?

using VueUiSparkbar.

this library is awesome.

thanks for any guidance.

**Comment by sombriks** [comment]
Ok i got a workaround:

```javascript

const receitaDespesaTotalPeriodo = computed(() => {
  const total = dashboardState.store.dashboard.receitaDespesaTotalPeriodo
    .reduce((acc, e) => {
      acc += e.value
      return acc
    }, 0)
  return dashboardState.store.dashboard.receitaDespesaTotalPeriodo.map(r => ({
    ...r,
    name: `${r.label} ${prepareMoney(r.value)}`,
    value: 100 * r.value / total,
  }))
})
```
and `styles.labels.value.show=false` in config.

**Comment by graphieros** [comment]
Hey:)

There are currently  no "prefix" and "suffix" config options for this component.
I'm going to fix that, as your use case clearly shows it's missing.

If I understand your use case correctly, you would ideally need to pass only the value in the dataset, which would be used as percentages for the bars, but with custom prefix | suffix.

Currently, using `style.layout.percentage: false`, and setting `style.layout.target` to the total  should allow you to pass only values, and draw bars as value / total automatically. The missing config option for prefix and suffix would remain, but when added, this combo should allow you to remove this additional computation.

I'll keep you posted here after I take a deeper look.

Cheers

**Comment by sombriks** [comment]
Hey, thanks a lot for that, will use that way, it simplifies many of my dashboard computed values!

**Comment by sombriks** [comment]
And id got gorgeous! Thanks again for the guidance!

```javascript
const receitaDespesaBarConfig = computed(() => {
  const total = dashboardState.store.dashboard.receitaDespesaTotalPeriodo
    .reduce((acc, e) => {
      acc += e.value
      return acc
    }, 0)
  return {
    style: {
      ...sparkBarConfig.style,
      layout: {
        ...sparkBarConfig.style.layout,
        independant: true,
        percentage: false,
        target: total
      }
    }
  }
})

const receitaDespesaTotalPeriodo = computed(() => {
  return dashboardState.store.dashboard.receitaDespesaTotalPeriodo.map(r => ({
    ...r,
    name: r.label,
    prefix: "R$ "
  }))
})
```

**Comment by graphieros** [comment]
You're welcome !
That's neat indeed.

The docs should probably have examples of such use cases, as it is not intuitive to toggle these config options to achieve this kind of result.

Thanks for using the lib, and for reaching out:)
