### ISSUE TITLE
Minor typo on "VueUiSparkstackbar"

### ISSUE THREAD

**Issue by sombriks** [graphieros/vue-data-ui#26]
![image](https://github.com/graphieros/vue-data-ui/assets/556695/b05789a2-ed0b-499c-9610-3ec45f4c1c65)

Docs present "VueUiSparkStackbar" but when i imported the chart i had to use "VueUiSparkstackbar"

![image](https://github.com/graphieros/vue-data-ui/assets/556695/e911f4ab-c3fe-463f-aaa2-8649d979a286)

**Comment by graphieros** [comment]
Thanks @sombriks :)
