### ISSUE TITLE
XY Chart Zoom color not customizable.

### ISSUE THREAD

**Issue by lovlyx** [graphieros/vue-data-ui#29]
Hello, first off, love the package, and truly appreciate your work!
I noticed that changing the zoom color does not affect the slider, no way to customize it via css whilst retaining the functionality as well.
![image](https://github.com/graphieros/vue-data-ui/assets/110987585/4d854fae-abec-48ed-bf81-732ad0858cc9)

Thank you again ♥️

**Comment by graphieros** [comment]
Hey @lovlyx :)

Thanks for reaching out. This has been on my radar for some time.

In addition to fixing the input color not working, the idea is to add a bunch of config options for the input, to contol its width, the radius of handles etc.

I'm currently passing through all configs of all components, so this fix will be treated after this step.
Will keep you posted.

Cheers

**Comment by graphieros** [comment]
@lovlyx fixed on [v2.1.72](https://github.com/graphieros/vue-data-ui/releases/tag/v2.1.72)

This fixes the config zoom.color not applied.
This input does the job, but its looks needs love; it's on the cards.

Thanks again for your issue:)

**Comment by lovlyx** [comment]
Thank you!!! 🥹

**Comment by graphieros** [comment]
@lovlyx I released [v2.1.77](https://github.com/graphieros/vue-data-ui/releases/tag/v2.1.77), with  improved zoom customization features.
