### ISSUE TITLE
Larger Gap between Bar Datasets in XY Chart

### ISSUE THREAD

**Issue by lovlyx** [graphieros/vue-data-ui#30]
When using 2+ bar datasets it is hard to distinguish the grouping since the padding is the same for elements within the group and outside of it.
![image](https://github.com/graphieros/vue-data-ui/assets/110987585/5093c2c7-3a49-4d17-8551-00765de6ed83)

It would be awesome if we could somehow control the x-gap value, or if the default one could be increased.
Here are some references for optimal gap between them:
![image](https://github.com/graphieros/vue-data-ui/assets/110987585/445ad0dd-6079-40fd-b0a9-efc537c817fb)

https://lumedataviz.com/chart-components/grouped-bar-chart/

Thank you again for the amazing work ❤️

**Comment by graphieros** [comment]
Hey @lovlyx :)
Thanks for your issue, it's indeed a nice feature to have.
After running some tests on a feature branch, it will be implemented soon.

I'll keep you posted.
Cheers

**Comment by lovlyx** [comment]
Thank you! Looking forward to it 👀

**Comment by graphieros** [comment]
@lovlyx you can update to [v2.1.90](https://github.com/graphieros/vue-data-ui/releases/tag/v2.1.90)

A new config attribute was added : `config.bar.periodGap` (default: 0.1)
For your specific use case, you might consider a value between 0.1 and 0.25

**Comment by graphieros** [comment]
@lovlyx you can update to [v2.1.90](https://github.com/graphieros/vue-data-ui/releases/tag/v2.1.90)

A new config attribute was added : `config.bar.periodGap` (default: 0.1)
For your specific use case, you might consider a value between 0.1 and 0.25
