### ISSUE TITLE
Live data change does not seem to work?

### ISSUE THREAD

**Issue by Zambiorix** [graphieros/vue-data-ui#46]
Hello,

How do I change datasets at regular intervals? I'm using vue-data-ui in a vue3/quasar project.

I've created a pie-chart that I want to update a regular intervals, but this doesn't seem to work.

Changing the dataset ref value with complete new data does not trigger a rerender.

This is also visible on your website in the (donut) chart builder. Adding new series does trigger a label update on the chart, but not the chart itself...

Thanks
Gerd

**Comment by graphieros** [comment]
Hi @Zambiorix :)

Thanks for pointing out this issue.

You can upgrade to[ v2.2.42](https://github.com/graphieros/vue-data-ui/releases/tag/v2.2.42) which fixes this bug.

Cheers!

**Comment by graphieros** [comment]
Hi @Zambiorix :)

Thanks for pointing out this issue.

You can upgrade to[ v2.2.42](https://github.com/graphieros/vue-data-ui/releases/tag/v2.2.42) which fixes this bug.

Cheers!

**Comment by Zambiorix** [comment]
Thanks, all works now.
BTW, your vue-data-ui library looks absolutely stunning... 🥇 
Fantastic work!
