### ISSUE TITLE
VueUiDonut translations block has no effect

### ISSUE THREAD

**Issue by Zambiorix** [graphieros/vue-data-ui#47]
```
translations: {
        total: 'foo',
        average: 'bar',
    },
```
has no effect

**Comment by graphieros** [comment]
Hey @Zambiorix :)

These translations are located in the following paths of the config object:

total
`style.chart.layout.labels.hollow.total.text`

average
`style.chart.layout.labels.hollow.average.text`

**Comment by Zambiorix** [comment]
Hi @graphieros 

Sorry, missed that ..

I was playing with:

https://vue-data-ui.graphieros.com/docs#vue-ui-donut

and noticed the `translations` block on the bottom that didn't seem to do anything.

Thanks!
