### ISSUE TITLE
Using "responsive: true", a blank area appears at the bottom of the chart component. 

### ISSUE THREAD

**Issue by lanwu114** [graphieros/vue-data-ui#50]
Dear Alec.
Using "responsive: true", a blank area appears at the bottom of the chart component. After calculation, the height of the blank area always remains at 24px.
I recorded a video. The first half of the video used 'vue data ui' and the second half of the video used 'HUIcharts'. I believe you can easily see that blank space.
![20240815_144226](https://github.com/user-attachments/assets/44f6ca90-a83e-43d7-abba-d1ffbd45cc09)

**Comment by graphieros** [comment]
Dear lanwu114,

Thank you for pointing out this issue.
Upgrading to **v2.2.54** should fix the problem.
