### ISSUE TITLE
VueUiXyConfig type has some properties with a wrong type

### ISSUE THREAD

**Issue by RudysCalderinDTx** [graphieros/vue-data-ui#52]
When using typescript, the IDE shows an error if rgb, hex, or any other color representation is used as value for highlightArea -> caption -> color property in config object. In VueUiXyConfig's type declaration, a type number is use that color property. This type of error also can be seen in properties that has a boolean type but it should be number.

![Screenshot 2024-08-21 150728](https://github.com/user-attachments/assets/634dc6fe-2668-465b-825f-5e3f7b6aa935)
![Screenshot 2024-08-21 150637](https://github.com/user-attachments/assets/16a67971-4b51-4b64-86ae-e6338ec8acc8)

**Comment by graphieros** [comment]
Hi @RudysCalderinDTx :)

You can upgrade to [v2.2.62](https://github.com/graphieros/vue-data-ui/releases/tag/v2.2.62)

Cheers

**Comment by RudysCalderinDTx** [comment]
Thanks @graphieros 

Great job on this library, by the way.
