### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by Azir-11** [graphieros/vue-data-ui#64]
Hello, I am from China and I noticed an error in the translation language selection dropdown while reading the document.
<img width="288" alt="image" src="https://github.com/user-attachments/assets/fe2ec8bf-11f8-4a6c-941f-22a0a276ded2">
This word means Chinese people, not Chinese.
The correct translation should be "中文"

**Comment by graphieros** [comment]
@Azir-11 thank you, it is now corrected
