### ISSUE TITLE
want 【Flight Seatmap with SVG】

### ISSUE THREAD

**Issue by makerForAll** [graphieros/vue-data-ui#66]
Hello, this is a great project.

However, compared to ECharts, it lacks certain features in some areas.

For example, in my project, I use SVG charts to manage rental situations. Something similar to this functionality:
https://echarts.apache.org/examples/en/editor.html?c=geo-seatmap-flight

It would be great if the author could implement this feature as it is something I really need.

I currently really like your project and have bookmarked it.

**Comment by graphieros** [comment]
Hi @makerForAll 

Thank you for your kind comments:)

The geo map feature is indeed lacking for the moment in Vue Data UI, as we have focused on the most common types of charts, with some other original types that don't exist in other libraries.

We are going to look into it, but rolling out full geo map features is not part of the roadmap for the moment.
