### ISSUE TITLE
 Chart-builder page code copy related

### ISSUE THREAD

**Issue by llds66** [graphieros/vue-data-ui#67]
Hello,Very good component library, I encountered a problem，within the Component code, I only want to copy the `config` data or `dateset` data generated by the chart-builder, but no matter what I copy, I copy the entire code.may I ask if you designed it this way?
![image](https://github.com/user-attachments/assets/b5c009ce-9f97-4a97-9cc8-6551da63c85a)

**Comment by graphieros** [comment]
Hi @llds66 :)
Yes it was designed to copy the whole component into your vue file.

I will add buttons to copy only config or dataset.

**Comment by llds66** [comment]
@graphieros Thank you so much

**Comment by graphieros** [comment]
@llds66 buttons are now available to copy only config or dataset.
