### ISSUE TITLE
Error in TextAlignTS type constraint in VueUiSparkbarConfig

### ISSUE THREAD

**Issue by zcodecn** [graphieros/vue-data-ui#72]
The type of VueUiSparkbarConfig.labels.name.position is TextAlign, which is defined in vue-data-ui.d.ts as export type TextAlign = "left" | "center" | "right"; there is no “top” value（The official example includes 'top'  ）, and the value 'center' and 'right'  it seems that the configurations for center and right do not have the expected effect。
```

 const config = ref<VueUiSparkbarConfig>({
  style: {
     
    labels: {
      fontSize: 12,
      name: {
        position: 'top', //TextAlign
        color: '#1A1A1A',
        bold:false

      },
      value: {
        show: true,
        bold:false
      }
    },

     
  }
});
```

**Comment by zcodecn** [comment]
There is also the rounding property in VueUiSparkbarDatasetItem; is this type a string or a number?

**Comment by graphieros** [comment]
@zcodecn I will fix that

- position: this is a type definition error. Possible values are "top" or "left".
- rounding: type is number

**Comment by graphieros** [comment]
@zcodecn you can upgrade to [v2.3.11](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.11) which fixes these type errors

**Comment by graphieros** [comment]
@zcodecn you can upgrade to [v2.3.11](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.11) which fixes these type errors

**Comment by zcodecn** [comment]
Thank you! You're releasing updates very quickly, and your components are really cool. I'll be using one or two charts in my project today, and there might be some other issues as well. I'll submit them as they come up.

**Comment by zcodecn** [comment]
I just updated to version 2.3.11. Currently, the definition of position is "top" | "left". I think a 'top-right' property can be add in the type definition, which would have the same effect as setting the current component to 'center', even though 'center' is not an accurate expression.
![1728037750426](https://github.com/user-attachments/assets/27028eba-e470-4385-a968-6ee37cc04860)

**Comment by zcodecn** [comment]
That sounds great

**Comment by graphieros** [comment]
@zcodecn you can upgrade to [v2.3.13](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.13) for the new positioning options
