### ISSUE TITLE
Can VueUiSparkHistogram configure individual colors for each data item?

### ISSUE THREAD

**Issue by zcodecn** [graphieros/vue-data-ui#73]
Currently, VueUiSparkHistogram allows configuring global gradient colors through style.bars.colors. Is it possible to configure individual colors for each data item while keeping the global gradient?

**Comment by graphieros** [comment]
@zcodecn indeed, currently the same color logic is applied to all datapoints. I can add a color attribute on VueUiSparkHistogramDatasetItem that would override the global color config for a given datapoint, while keeping the gradient features. I will wait for further requests to work on this improvement, as you told me you would probably have more to ask ;)

**Comment by zcodecn** [comment]
Sure, you can release it after tomorrow.If I encounter any other issues during use today, I'll submit them as well.

**Comment by zcodecn** [comment]
Thx , I will try it out later
