### ISSUE TITLE
The bar overflow when there is a large disparity in the dataset of VueUiSparkBar 

### ISSUE THREAD

**Issue by zcodecn** [graphieros/vue-data-ui#74]
When the proportions of data items are highly disparate, the data bar chart overflows. Even though I set max-width on the outer div, it has no effect. This bug can be reproduced in the configuration page on the official website.
![image](https://github.com/user-attachments/assets/dfe696fb-18e4-41c9-8058-e1649361300a)

**Comment by graphieros** [comment]
Hi @zcodecn

960% will overflow with this configuration. (To hack the css you would need to target the svg and set it to overflow: visible).

I think in this case the bar should look like it's full (having it overflow the chart is not pretty). I can change the code so it looks like this in this case:
<img width="582" alt="Capture d’écran 2024-10-05 à 05 55 40" src="https://github.com/user-attachments/assets/f808fb96-df52-47a5-b6a7-341f89daee10">

To achieve this with the current version, you need to specify an individual target on the datapoint. If the value exceeds 100 then the target == value and the bar is full without overflowing:

![image](https://github.com/user-attachments/assets/7149c805-7592-4690-bbf5-240d6ed3b9dc)

**Comment by graphieros** [comment]
@zcodecn you can upgrade to [v2.3.14](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.14) which fixes this issue
