### ISSUE TITLE
VueUiKpi component does not refresh when responsive data changes

### ISSUE THREAD

**Issue by salarxiao321** [graphieros/vue-data-ui#78]
- "vue": "^3.3.7"
- "vue-data-ui": "^2.3.17"  or "vue-data-ui": "^2.3.24"

`
<script setup>
import { ref } from "vue";
import { VueDataUi } from "vue-data-ui";
import "vue-data-ui/style.css";

const config = ref({
  animationFrames: 60,
  animationValueStart: 0,
  backgroundColor: "#FFFFFF",
  fontFamily: "inherit",
  layoutClass: "p-4 m-4 rounded-md shadow",
  layoutCss: "",
  prefix: "",
  suffix: "",
  title: "Title",
  titleBold: true,
  titleColor: "#1A1A1A",
  titleClass: "",
  titleCss: "",
  titleFontSize: 16,
  useAnimation: true,
  valueBold: true,
  valueColor: "#6376DD",
  valueClass: "",
  valueCss: "",
  valueFontSize: 32,
  valueRounding: 0,
});

const dataset = ref(18);

// 生成 1 到 20 之间的随机数
const getRandomNumber = () => {
  return Math.floor(Math.random() * 20) + 1;
};

// 定时更新 dataset 的值
const updateDataset = () => {
  dataset.value = getRandomNumber();
};

// 设置定时器
let intervalId;

const startTimer = () => {
  intervalId = setInterval(updateDataset, 5000); // 每 5 秒更新一次
};

const stopTimer = () => {
  if (intervalId) {
    clearInterval(intervalId);
  }
};

// 在组件挂载时启动定时器
onMounted(() => {
  startTimer();
});

// 在组件卸载时停止定时器
onUnmounted(() => {
  stopTimer();
});
</script>

<template>
  <div style="width: 600px">
    <VueDataUi component="VueUiKpi" :config="config" :dataset="dataset" />
    <p style="color: white">{{ dataset }}</p>
  </div>
</template>
`

**Comment by graphieros** [comment]
Hi @salarxiao321 

You can upgrade to [v2.3.25](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.25) which fixes this issue

**Comment by husayt** [comment]
hi, still see this issue wit wordCloud component in version 2.6.13. Updating dataset, doesn't update the chart.

Thanks

**Comment by graphieros** [comment]
@husayt 

Thanks, this will be fixed asap.

**Comment by graphieros** [comment]
@husayt 

Fixed in v2.6.14
