### ISSUE TITLE
VueUiQuickChart    Version 2.3.24, legend display abnormal ，   2.3.17  not have this problem

### ISSUE THREAD

**Issue by salarxiao321** [graphieros/vue-data-ui#79]
1. 2.3.17

<img width="1703" alt="image" src="https://github.com/user-attachments/assets/f9344fec-3bcc-4591-8064-af1d46f10d2b">

1. 2.3.24

<img width="1708" alt="image" src="https://github.com/user-attachments/assets/9e0227b7-1e3a-4fa3-9cab-46a904a78120">

**Comment by graphieros** [comment]
Hi @salarxiao321 

I cannot reproduce the issue using 2.3.24.
Please provide the config object you are using, and confirm you imported the css.

**Comment by salarxiao321** [comment]
2.3.25   have fixed
