### ISSUE TITLE
dataLabels format

### ISSUE THREAD

**Issue by martinfruehmorgen** [graphieros/vue-data-ui#85]
Hello,
Thank you so much for this library!

Is there a way to add a custom format for the dataLabels here:

```js
dataLabels: {
  show: true,
  adaptColorToBackground: true,
  color: '#1A1A1A',
  fontSize: 11,
  bold: false,
  rounding: 2,
  prefix: '',
  suffix: ' €'
}
```

If I have series f.e. with [200100,20, 29111,12]
I would like to have it displayed like this:
200.100,20 €
291.11,12 €

With the options we have I think this is not possible?

Thanks!
Martin

**Comment by graphieros** [comment]
Hi @martinfruehmorgen :)

It looks like you are using `VueUiStackbar`.

The way you configured dataLabels is correct, and should display the suffix as expected.

Unless you are using `distributed: true`, in which case you must set `showDistributedPercentage: false` to show dataLabels as values and not percentages.

Let me know if this helps, if not, please provide screenshots, datasets and configs so I can reproduce.

Cheers

**Comment by graphieros** [comment]
Hi @martinfruehmorgen :)

Numbers are currently formatted toLocaleString with the default implementation (no locale param passed).

Thank you for your question, as this can be an additional config option to add to all charts with dataLabels. I'll let you know when it is rolled out.

Cheers

**Comment by martinfruehmorgen** [comment]
Thank you! I think it would be a great option to customize the label with a callback like with echarts
https://echarts.apache.org/en/option.html#series-line.label.formatter

Thanks!
Martin
