### ISSUE TITLE
Add another gender option in the age pyramid chart

### ISSUE THREAD

**Issue by cyrilf** [graphieros/vue-data-ui#87]
Hey,

I was wondering if there is any "easy" way of adding a new gender option in the `VueUiAgePyramid`.

Currently it's defined as `year | age | number women | number men ` but I would need to add a third option `number nc` (or not communicated).
But if it's too complicated, maybe this chart type isn't appropriate for my use case.
Let me know.

----

I will open a second issue related to this and to my use case.
Relates to: #88

**Comment by graphieros** [comment]
Hi @cyrilf 

The age pyramid component is indeed designed as the statistical traditional data viz to represent populations by their gender at birth, so it is not appropriate to your use case.

Improvements will come in other components to answer this use case.
