### ISSUE TITLE
Support negative values in Vertical Bar or Stack bar charts

### ISSUE THREAD

**Issue by cyrilf** [graphieros/vue-data-ui#88]
When using the awesome [Chart builder](https://vue-data-ui.graphieros.com/chart-builder) site, it seems like

`VueUiVerticalbar` and `VueUiStackbar` doesn't support negative values correclty.

| VueUiVerticalbar | VueUiStackbar |
|-|-|
| ![image](https://github.com/user-attachments/assets/0d375767-7daa-4a4d-97a4-e6ffc8a846c5) | ![image](https://github.com/user-attachments/assets/98ea0eee-6885-4569-8b40-19355e6a9778) |

From quickly checking in the code, it seems like [this line](https://github.com/graphieros/vue-data-ui/blob/7f50d165b796788ac7f53a8572a5c179e2d9fd6b/src/components/vue-ui-stackbar.vue#L237) always start the axis at 0 and not the min value.
Maybe that's a good start to investigate.

----

Context:

In my current project, I'm using ApexCharts; and in order to achieve an age pyramid with 3 gender types, I have to use a Horizontal Stack bar, with one serie having negative values (to appears on the left) and the two other ones, positive values (to be on the right). (I then use `Math.abs` in all formatters to display the correct value (labels, tooltips and so on) I haven't checked yet, but I believe your library supports these customization too?).
Obviously, that's not perfect, as the third one should be balanced between left and right, but for now, that does the job.
You can see the results in this picture:

![Screenshot from 2024-10-10 15-14-06](https://github.com/user-attachments/assets/570dc459-e978-44bf-b3bf-adc31c8bc17e)

Relates to #87

----

### Side note:

Thanks for this lib, that's an impressive amount of work. :sparkles:  (I just discovered it and I'm considering it for an ongoing project).

**Comment by graphieros** [comment]
HI @cyrilf :)

Currently both of these charts don't support negative values.
I've been considering to change this for a while now, so your issues are a good incentive to do so.

I'll keep you posted when it's rolled out.

PS. Et merci pour les encouragements :)

**Comment by graphieros** [comment]
@cyrilf 

You can upgrade to [v2.3.33](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.33) which adds support for negative values for **VueUiStackbar** and **VueUiVerticalBar**

Documentation website is up to date, here is VueUiStackBar in action:


https://github.com/user-attachments/assets/18bd091b-c77e-4baf-bbf6-1b781ea57316

**Comment by cyrilf** [comment]
Oh woah! :sparkles: 
I felt like you were going to be reactive.. but that's.. VERY FAST! :smile: 

Thanks a lot for that, I'll have a look on my freetime, very very nice! :clap:

**Comment by graphieros** [comment]
@cyrilf you are welcome:)

I do think there is still room for a new component that can make pyramid-like bars with multiple series, that is properly centered.

**Comment by graphieros** [comment]
Hey @cyrilf 

I think you might be interested in the addition made to VueUiStackbar in [v2.3.45](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.45)

**Comment by cyrilf** [comment]
Hey, thanks for notifying me and thanks for this new option.
Indeed, that's really cool!
I've just opened a [PR#5 in the doc website](https://github.com/graphieros/vue-data-ui-doc/pull/5) to be able to add a new serie into the dataset (so that I can try to add a 3rd serie and see the rendering for my "pyramid" use case).

**Comment by cyrilf** [comment]
I think the missing things to completly match my previously shared screenshot in this issue thread would be:

- Add a min/max option for the `xAxis` so that it spreads evenly
- Add a formatter for the xAxis (to use `Math.abs` on the negative values)
- Add a formatter for the tooltip content values (to use `Math.abs` on the negative values)
- Add a formatter for the data table values (to use `Math.abs` on the negative values)

**But**, honestly, I think that using 3 series with positive values would do the trick and avoid all these required complexities.
Especially because my final render still has the issue where the bar of the "Non renseigné" is on the right side and not balanced.
I just need to negociate this with the client 😉
So, we're good! 😃 

Thanks for all the efforts in making this horizontal StackBar possible 👌

**Comment by graphieros** [comment]
@cyrilf 
I added scaleMin and scaleMax config attributes to VueUiStackbar in [v2.3.46](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.46).
As for the complexities you referred to in you previous message, it does look artificial. I'm still thinking of a new component that would show centered bars. It's an interesting challenge, we'll see.

**Comment by cyrilf** [comment]
Haha, awesome! Thanks!
As for the new component, I don't know. We went for the pyramid chart at first because it makes perfect sense for these kind of visualizations. But now that the requirements have changed, I think that a normal horizontal stack bar is enough.
I'm not sure that a component showing centered bars would make more sense. I don't think it would be easier to get the information (especially because of the x scales).

**Comment by graphieros** [comment]
I agree with your take regarding your use case.

After giving it some thought, centered bars would not be very readable anyways. It's already hard for the eyes to use a classic stacked bars, so introducing variable x scales for each row would make a mess of it all.

I'm glad your requirements are inline with a more traditional chart type:)
