### ISSUE TITLE
[VueUiSparkline] How should I configure the height of the chart to fill the divbox?

### ISSUE THREAD

**Issue by colaiven** [graphieros/vue-data-ui#90]
my components

```
<div style="width:500px;height: 300px;border: 1px solid red">
    <VueDataUi component="VueUiSparkline" :dataset="dataset" :config="config"/>
</div>
```

How to fill 100% the height？

![image](https://github.com/user-attachments/assets/a0085b32-7b2f-46ee-9ce3-f42bdac8b5d1)

**Comment by graphieros** [comment]
Hi @colaiven 

This component is designed to scale based on the width of the container.
In your case, you should solve it with css.

```html
<div style="width:500px;height: 300px;border: 1px solid red; display: flex; align-items:center; background: #1A1A1A;">
    <VueDataUi component="VueUiSparkline" :dataset="dataset" :config="config"/>
</div>
```

**Comment by graphieros** [comment]
@colaiven 
If you want, you can upgrade to [v2.3.44](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.44) which adds the responsive config attribute, to see if you prefer this solution.
