### ISSUE TITLE
 9/5000 Does the chart not support floating point numbers?

### ISSUE THREAD

**Issue by Zhengjun-Shu** [graphieros/vue-data-ui#92]
Does the chart not support floating-point drawing? I didn't find a setting to configure floating-point numbers, causing the chart to appear as an integer even when I passed in floating-point numbers.

**Comment by graphieros** [comment]
@Zhengjun-Shu 
You need to use `rounding` or `roundingValue` or `roundingPercentage` config attributes in the config object passed in the config prop, depending on the chart you are using.
